# **Numpy Arrays**

In [87]:
import numpy as np

## **Creating Numpy arrays**

In [88]:
#1D array
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [89]:
#2D array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [90]:
#3D array
arr2=np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(arr2)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


In [91]:
print(type(arr))

<class 'numpy.ndarray'>


## **Checking Dimension**

In [92]:
#Checking dimension
arr.ndim

1

## **Accessing Array elements**

In [93]:
#Accessing array elements
print(arr[0])
print(arr1[0,0])
print(arr2[0,0,1])

1
1
2


In [94]:
#modifying array elements
arr[4]=6
print(arr)

[1 2 3 4 6]


In [95]:
#Slicing 1D array
print(arr[0:3])

[1 2 3]


## **Some numpy array methods**

In [96]:
#copy of an array
x= arr.copy()
x[0]=10
print(x)
print(arr)

[10  2  3  4  6]
[1 2 3 4 6]


In [97]:
#reference of an array
y=arr.view()
y[0]=10
print(y)
print(arr)

[10  2  3  4  6]
[10  2  3  4  6]


In [98]:
#no of elements in each dimension
print(arr1.shape)

(2, 3)


In [99]:
#changing shape of an array
a=np.array([1,2,3,4,5,6])
new = a.reshape(2,3)
print(new)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## **Iterating over Array**

In [100]:
#iterating over 1D array
arry=np.array([1,2,3,4,5])
for x in arry:
    print(x)

1
2
3
4
5


In [101]:
#iterating over 2D array
arry = np.array([[1, 2, 3], [4, 5, 6]])
for x in arry:
    print(x)

[1 2 3]
[4 5 6]


## **Joining the arrays**

In [102]:
#concatinating 1D arrays
a= np.array([1,2,3])
b= np.array([11,12,13])
c= np.concatenate((a,b),axis=0)
print(c)

[ 1  2  3 11 12 13]


In [103]:
#concatinating 2D arrays
a= np.array([[1,2,3],[4,5,6]])
b= np.array([[11,12,13],[14,15,16]])

new= np.concatenate((a,b),axis=0)
print(new)

print()

new1= np.concatenate((a,b),axis=1)
print(new1)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


In [104]:
#Stacking 1D arrays
a= np.array([1,2,3])
b= np.array([11,12,13])

new= np.stack((a,b),axis=0)
print(new)

print()

new1= np.stack((a,b),axis=1)
print(new1)

[[ 1  2  3]
 [11 12 13]]

[[ 1 11]
 [ 2 12]
 [ 3 13]]


In [105]:
#stacking 2D arrays
a= np.array([[1,2,3],[4,5,6]])
b= np.array([[11,12,13],[14,15,16]])

new= np.stack((a,b),axis=0)
print(new)

print()
print()

new1= np.stack((a,b),axis=1)
print(new1)

print()
print()

new2= np.stack((a,b),axis=2)
print(new2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


[[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [14 15 16]]]


[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]]


## **Splitting Array**

In [115]:
#splitting 1D array
arr= np.array([1,2,3,4,5,6])
new= np.array_split(arr, 3)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [112]:
print(type(new))

<class 'list'>


In [114]:
#splitting 2D array
arr= np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
new= np.array_split(arr, 2)
print(new)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


## **Searching**

In [125]:
#finding the indices of a value
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print(arr == 4)

new = np.where(arr == 4)
print(new)

[False False False  True False  True  True]
(array([3, 5, 6]),)


In [128]:
#getting the index where the specified value would be inserted to maintain the search order.
arr = np.array([1,3,5,8])
x = np.searchsorted(arr, 3)
print(x)

#The searchsorted() method is assumed to be used on sorted arrays.

1


## **Sorting an array**

In [131]:
#sorting 1D array
arr = np.array([3, 2, 0, 1])
new = np.sort(arr)
print(new)

[0 1 2 3]


In [132]:
#sorting a string array
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [133]:
#sorting 2D array
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## **Filtering an array**

In [134]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]

print(newarr)

[41 43]
