# **Numpy random**

In [1]:
import numpy as np
from numpy import random

## **Generating random numbers**

In [2]:
#random integer from 0-100
print(random.randint(100))

96


In [3]:
#random float between 0-1
print(random.rand())

0.9954271129686453


In [4]:
#random 1D array containing 5 integers from 0-100
x= random.randint(100, size=(5))
print(x)

[25  9 87 53 95]


In [5]:
#random 2D array with 3 rows each row containing 5 integers from 0-100
x = random.randint(100, size=(3, 5))
print(x)

[[76 45 39 55 24]
 [17 70 78 48 35]
 [89 50 42 47 32]]


In [6]:
#random 1D array containing 5 floats from 0-1
print(random.rand(5))

[0.02230556 0.70893072 0.09273878 0.55869552 0.63571263]


In [7]:
#random 2D array with 3 rows each row containing 5 floats from 0-1
print(random.rand(3,5))

[[0.33380548 0.61769972 0.93593764 0.97727305 0.12299911]
 [0.89661091 0.76680376 0.64595539 0.12309517 0.92890345]
 [0.36985456 0.15968246 0.59910733 0.08148182 0.86581482]]


In [8]:
#generating random number from array
x= random.choice([1,2,3,4,5])
print(x)

4


In [9]:
#Generating a 1-D array that consists of the values in the array parameter (3, 5, 7, and 9):
x = random.choice([3, 5, 7, 9], size=(3))
print(x)

[7 7 5]


In [10]:
#Generating a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
x = random.choice([3, 5, 7, 9], size=(3,5))
print(x)

[[5 7 5 7 9]
 [5 7 5 5 5]
 [3 5 5 7 5]]


## **Random Distribution**

In [11]:
#generate random numbers based on defined probabilities
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(10))
print(x)

[3 7 7 7 7 3 7 7 7 3]


## **Random Permutations**

In [12]:
#changing arrangement of elements in-place. i.e. in the array itself
arr= np.array([1,2,3])
random.shuffle(arr)
print(arr)

[2 1 3]


In [13]:
#Generating a random permutation of elements of following array
arr= np.array([1,2,3])
new = random.permutation(arr)
print("Original array:", arr)
print("New array:",new)

Original array: [1 2 3]
New array: [3 2 1]


## **Normal Distribution**

In [14]:
#generating a random number from a standard normal distribution with mean = 0 and standard deviation = 1
x = random.normal(loc=0, scale=1, size=None)
print(x)

0.4681051677450912


In [15]:
#generating a 1-D array of five random numbers drawn from a normal distribution with mean = 0 and standard deviation = 1
arr = random.normal(size=5)
print(arr)

[ 1.86505226 -0.08178715  0.17449556  0.27134158 -0.41185016]


In [16]:
#generating a 2-D array of size 2x3 of random numbers drawn from a normal distribution with mean = 1 and standard deviation = 2
x = random.normal(loc=1, scale=2, size=(2, 3))
print(x)

[[-0.07286914 -0.59880471  0.18728335]
 [ 0.52993679  0.32222475 -1.75419491]]


## **Binomial Distribution**

In [25]:
#generating a 1-D array of 10 random numbers drawn from a binomial distribution with no. of trials(n)=10 and p=0.5
x= random.binomial(n=10, p=0.5, size=10)
print(x)

[7 3 5 5 2 4 4 4 4 7]


## **Multinomial Distribution**
(Generalization of Binomial distribution)

In [46]:
x = random.multinomial(n=10, pvals=[1/6, 1/6, 1/6, 1/6, 1/6,1/6], size=3)
print(x)

[[3 2 4 1 0 0]
 [2 2 2 1 2 1]
 [3 2 2 1 0 2]]


## **Poisson Distribution**

In [47]:
#generating a 1-D array of 10 random numbers drawn from a Poisson distribution with average rate=2
x = random.poisson(lam=2, size=10)
print(x)

[1 4 2 2 2 1 0 4 3 1]


## **Uniform Distribution**

In [48]:
#generating 1D array of five random numbers in the range 10(inclusive) to 20(exclusive)
x = np.random.uniform(low=10, high=20, size=5)
print(x)

[17.34846594 14.53433182 13.1041447  10.5716027  19.41776565]


## **Logistic Distribution**

In [49]:
x = random.logistic(loc=1, scale=2, size=(2, 3))
print(x)

[[-3.57209126  1.547085    2.48984841]
 [ 1.57319852 -3.12989121  1.81935407]]


## **Exponential Distribution**

In [50]:
x = random.exponential(scale=2, size=(2, 3))
print(x)

[[0.18490151 3.80883165 0.39343708]
 [4.76229369 2.16796677 1.53409408]]


## **Chi Squared Distribution**

In [51]:
#generating a 2-D array of size 2x3 of random numbers drawn from a Chi squared distribution with degree of freedom=2
x = random.chisquare(df=2, size=(2, 3))
print(x)

[[3.45857745 0.35674815 2.06960286]
 [0.49323018 1.5558565  3.49845551]]
